name: Load DHWP
version: "1.0.2"
slug: load_dhwp
description: "DHWP Loader"
startup: once
boot: manual
url: "https://github.com/OliverJ-io/ha-repo/tree/main/detailed_hello_world_push_loader"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
schema:
  channel: list(current)?
map:
  - homeassistant_config:rw